apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - prod
          - qa
          - dev
  template:
    metadata:
      name: nginx
      labels:
        app: nginx # harus match dengan key value yang ada di matchExpressions
        env: prod # harus match dengan key value yang ada di matchExpressions
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80